### ISSUE TITLE
Визуальное отображение новостей

### ISSUE THREAD

**Issue by kleonova** [sumbad/SMS_IVC_RZD#6]
Модальные окна в новостях с малым содержимым открываются некорректно 

![image](https://cloud.githubusercontent.com/assets/12046058/8768570/113a4198-2e8e-11e5-9982-8862c54640e6.png)

**Comment by sumbad** [comment]
Протестировать после merge

**Comment by sumbad** [comment]
Изображение убрано из диалогового окна, задача неактуальна.
