### ISSUE TITLE
Некорректное отображение кнопки загрузки файлов

### ISSUE THREAD

**Issue by kleonova** [sumbad/SMS_IVC_RZD#7]
На странице /articles/Create

**Comment by kleonova** [comment]
![image](https://cloud.githubusercontent.com/assets/12046058/8768585/b32c522a-2e8e-11e5-8929-214a7db2001d.png)

**Comment by sumbad** [comment]
Добавил тег <noscript> в:

<noscript><link href="~/Scripts/components/jQuery-File-Upload-9.10.1/css/jquery.fileupload-ui-noscript.css" rel="stylesheet" /></noscript>
<noscript><link href="~/Scripts/components/jQuery-File-Upload-9.10.1/css/jquery.fileupload-noscript.css" rel="stylesheet" /></noscript>
